//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Govno_2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGroup
    {
        public SGroup()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Services> Services { get; set; }
    }
}
